project:
  type: website
  output-dir: _site
  include:
    - index.qmd
    - "*.md"

execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  pdf: default
  docx: default



