---
title: "Data Verification"
format: html
---

## Gamelogs

```{r}
library(tidyverse)
wnba_gl <- read_rds(here::here("data/wnba_gl.rds"))
```

```{r}
wnba_gl |>
  group_by(season_id) |>
  summarize(
    num_teams = n_distinct(team_id),
    num_games = n(),
    num_wins = sum(win_flag, na.rm = TRUE),
    mean_wpct = sum(win_flag, na.rm = TRUE) / n(),
    mean_win_prob = mean(home_win_prob),
    mean_rolling_wins = mean(rolling_wins_44),
    mean_attendance = mean(attendance, na.rm = TRUE),
    missing_attendance = sum(is.na(attendance)),
    num_cc = sum(is_cc, na.rm = TRUE),
    num_active = sum(is_active)
  ) |>
  print(n = Inf)
```

## EDA

```{r}
ggplot(wnba_gl, aes(x = elo.A, y = elo.B, color = attendance)) +
  geom_point()
```

```{r}
ggplot(wnba_gl, aes(x = max_elo, y = attendance, color = factor(is_cc))) +
  geom_point() +
  geom_smooth(method = "lm") + 
  facet_wrap(vars(season_id))
```

```{r}
ggplot(wnba_gl, aes(x = max_elo, y = attendance / arena_capacity, color = factor(is_cc))) +
  geom_point() +
  geom_smooth(method = "lm") + 
  facet_wrap(vars(season_id))
```


```{r}
ggplot(wnba_gl, aes(x = rolling_wins_44, color = season_id)) +
  geom_vline(xintercept = 22, linetype = 3) +
  geom_density()
```

```{r}
ggplot(wnba_gl, aes(x = rolling_wins_44)) +
  geom_vline(xintercept = 22, linetype = 3) +
  geom_density() +
  facet_wrap(vars(name_current))
```

```{r}
ggplot(wnba_gl, aes(y = attendance, x = rolling_wins_44, color = is_cc)) +
  geom_point() +
  facet_wrap(vars(name_current))
```

```{r}
ggplot(wnba_gl, aes(x = game_date, y = attendance, color = factor(is_cc))) +
  geom_point() +
  facet_wrap(vars(name_current))
```

```{r}
ggplot(wnba_gl, aes(x = game_date, y = elo.A, color = factor(is_cc))) +
  geom_point() +
  facet_wrap(vars(name_current))
```


```{r}
wnba_gl |>
  summarize(cor = cor(elo.A, rolling_wins_44))

ggplot(wnba_gl, aes(x = rolling_wins_44, y = elo.A)) +
  geom_point() +
  facet_wrap(vars(name_current))

ggplot(wnba_gl, aes(x = elo.A, y = attendance, color = factor(is_cc))) +
  geom_point() +
  facet_wrap(vars(name_current))

```


## Modeling

```{r}
# Consider this alternative model specification
mod_attendance <- lm(
  log(attendance + 1) ~ home_win_prob + factor(wday(game_date)) + factor(month(game_date)) + name_current + season_id + is_cc,
  data = filter(wnba_gl, !season_id %in% c(2021), is_active)
)

summary(mod_attendance)
anova(mod_attendance)

# plot(mod_attendance)
```

```{r}
attendance_model <- lm(
  attendance ~ rolling_wins_44 + factor(wday(GAME_DATE)) + factor(month(GAME_DATE)) + TEAM_ID + SEASON_ID + is_cc + arena_capacity,
  data = filter(wnba_gl, !SEASON_ID %in% c(22021))
)

summary(attendance_model)
```

## determining period definitions

```{r}
continuous_model <- lm(
  log(attendance + 1) ~
    (home_win_prob + elo.B)*as.factor(season_id) + factor(wday(game_date)) + factor(month(game_date)) + team_id + is_cc + arena_capacity,
  data = filter(wnba_gl, !season_id %in% c(2021), is_active)
)

summary(continuous_model)
```
```{r}
wnba_gl <- wnba_gl|>
  mutate(period = case_when(
  season_id <= 2002 ~ "97-02",
  season_id <= 2009 ~ "03-09",
  season_id <= 2014 ~ "10-14",
  season_id <= 2019 ~ "15-19",
  TRUE ~ "modern"
))

period_model <- lm(
  log(attendance + 1) ~
    (home_win_prob + elo.B)*period + factor(wday(game_date)) + factor(month(game_date)) + team_id + is_cc + arena_capacity,
  data = filter(wnba_gl, !season_id %in% c(2021), is_active)
)

summary(period_model)
```
```{r}
continuous_model_simple <- lm(
  attendance ~
    (home_win_prob + elo.B)*as.factor(season_id),
  data = wnba_gl
)

library(tidyverse)

pred_data <- expand_grid(
  home_win_prob = seq(0.2, 0.8, length.out = 100),
  season_id = sort(unique(wnba_gl$season_id)),
  elo.B = mean(wnba_gl$elo.B, na.rm = TRUE)  
)

pred_data <- pred_data |>
  filter(!season_id %in% c(2020, 2021))|>
  mutate(
    season_id = factor(season_id),
    pred_log_attendance = predict(continuous_model_simple, newdata = cur_data())
  )

ggplot(pred_data, aes(
  x = home_win_prob,
  y = pred_log_attendance,
  group = season_id,
  color = season_id
)) +
  geom_line(alpha = 0.7) +
  labs(
    x = "Home Win Probability",
    y = "Predicted log(Attendance + 1)",
    color = "Season",
    title = "Changing Effect of Team Strength on Attendance Over Time"
  )  +
  theme_minimal()
```



```{r}
library(marginaleffects)

valid_seasons <- sort(unique(wnba_gl$season_id[!wnba_gl$season_id %in% c(2020, 2021)]))


slopes_data <- slopes(
  continuous_model,
  variables = c("home_win_prob", "elo.B"),
  newdata = datagrid(season_id = valid_seasons)
)

slopes_data <- as.data.frame(slopes_data)

#slopes_data <- slopes_data |>
#  mutate(
#    term = recode(term,
#                      "home_win_prob" = "Home Win Probability",
#                      "elo.B" = "Opponent's Elo Rating")
#  )|

ggplot(slopes_data, aes(x = season_id, y = estimate, color = term, fill = term, group = term)) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.2) +
  geom_point(size = 2) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  facet_wrap(~ term, scales = "free_y", ncol = 1) +
  labs(
    x = "Season",
    y = "Marginal Effect on log(Attendance+1)",
    color = "Team Strength Measure",
    fill = "Team Strength Measure",
    title = "How the Impact of Team Strength on Attendance Changes by Season"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

- the first wnba teams to fold were the miami sol and the portland fire (2003)